#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Dynamically updates the IPv4/IPv6 DNS records for domains registered with Loopia.
https://joelpurra.com/projects/loopia-api-dyndns/

Based on Loopia API's official sample script.
https://support.loopia.se/wiki/uppdatera-dynamisk-ip-adress-med-loopiaapi/
"""

import ipaddress
import os
import logging
import urllib.request
import xmlrpc.client
import time

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)

logger = logging.getLogger(__name__)

class Config:
    try:
        username = os.environ["LOOPIA_API_USERNAME"]
        password = os.environ["LOOPIA_API_PASSWORD"]
        domain = os.environ["LOOPIA_DOMAIN"]
        subdomain = os.environ["LOOPIA_SUBDOMAIN"]
        ip6_enable = os.environ.get("LOOPIA_IP6_ENABLE", "False").lower() == "true"
    except KeyError as exception:
        logger.error(
            "Could not read configuration from environment variable: {exception}".format(
                exception=exception,
            )
        )
        quit(1)

    fqdn = domain if subdomain == "@" else subdomain + "." + domain

    check_ipv4_url = "https://api.ipify.org/"
    check_ipv6_url = "https://api6.ipify.org/"
    loopia_api_xml_rpc_url = "https://api.loopia.se/RPCSERV"


def api_error(exception):
    logger.error(
        "Request to Loopia API failed: {exception}".format(
            exception=exception,
        )
    )


def get_string_value_from_url(url, max=None):
    try:
        return urllib.request.urlopen(url).read(max).decode("utf-8").strip()
    except:
        logger.error(
            "Could not get IP from url: {url}".format(
                url=url,
            )
        )


def get_public_ipv4():
    ipv4str_from_url = get_string_value_from_url(Config.check_ipv4_url, 15)
    try:
        return str(ipaddress.IPv4Address(ipv4str_from_url))
    except:
        logger.error(
            "Could not parse IPv4 address: {ipv4str}".format(
                ipv4str_from_url=ipv4str_from_url,
            )
        )


def get_public_ipv6():
    ipv6str_from_url = get_string_value_from_url(Config.check_ipv6_url, 45)
    try:
        return str(ipaddress.IPv6Address(ipv6str_from_url))
    except:
        logger.error(
            "Could not parse IPv6 address: {ipv6str}".format(
                ipv6str_from_url=ipv6str_from_url,
            )
        )


def get_records(recordType):
    try:
        zone_records = client.getZoneRecords(
            Config.username,
            Config.password,
            Config.domain,
            Config.subdomain,
        )
    except Exception as exception:
        api_error(exception)

    # Remove irrelevant records and return.
    return [d for d in zone_records if d["type"] == recordType]


def update_record(value, record):
    status = "No change"

    # Does the record need updating?
    if record["rdata"] != value:
        # Setting record_id updates an existing record.
        new_record = {
            "priority": record["priority"],
            "rdata": value,
            "record_id": record["record_id"],
            "ttl": record["ttl"],
            "type": record["type"]
        }

        try:
            status = client.updateZoneRecord(
                Config.username,
                Config.password,
                Config.domain,
                Config.subdomain,
                new_record,
            )
        except Exception as exception:
            api_error(exception)

    logger.info(
        "{fqdn} {recordType}: {status} ({value})".format(
            fqdn=Config.fqdn,
            recordType=record["type"],
            status=status,
            value=value,
        )
    )


def check_and_update_record(recordType, value):
    """Fetch a single record and update it"""
    records = get_records(recordType)
    recordCount = len(records)

    if recordCount != 1:
        logger.error(
            "Require exactly one {recordType} record for {fqdn}, but found {recordCount}.".format(
                fqdn=Config.fqdn,
                recordCount=recordCount,
                recordType=recordType,
            )
        )

    update_record(value, records[0])


if __name__ == "__main__":
    client = xmlrpc.client.ServerProxy(
        uri=Config.loopia_api_xml_rpc_url,
        encoding="utf-8",
    )

    try:
        while True:
            try:
                public_ipv4 = get_public_ipv4()
                check_and_update_record("A", public_ipv4)
            except Exception as e:
                logger.error(f"Dynamic DNS update failed: {e}")

            if(Config.ip6_enable):
                try:
                    public_ipv6 = get_public_ipv6()
                    check_and_update_record("AAAA", public_ipv6)
                except Exception as e:
                    logger.error(f"Dynamic DNS update failed: {e}")

            time.sleep(20 * 60) # 20 minutes

    except KeyboardInterrupt:
        logger.info("Shutting down...")
